version: 2.1
orbs:
  node: circleci/node@4.0.0

jobs:
  checkout_and_unit_test:
    docker:
      - image: cimg/node:15.8.0
    steps:
      - checkout
      - run: node --version
      - run: npm --version
      - run: npm install
      - run: npm run test
      
integration:

workflows:
  workflowIntegration:
    jobs:
      - checkout_and_unit_test
      - integration:
          requires:
            - checkout_and_unit_test
