version: 2.1
orbs:
  node: circleci/node@4.0.0

jobs:
  checkout_and_unit_test:
    docker:
      - image: cimg/node:15.8.0
    steps:
      - checkout
      - run: node --version
      - run: npm --version
      - run: npm install
      - run: npm run test

  integration:
    docker:
      - image: cimg/node:15.8.0
    steps:
      - run: git clone https://github.com/DanCoul/c03-backend.git
      - run: git clone https://github.com/DanCoul/c03-frontend.git 
      - run: cd c03-frontend/ && npm install && npm run build
      - run: cp -r c03-frontend/build c03-backend/ && cd c03-backend/ && ls -al
      - run: echo "déploiement"


workflows:
  workflowIntegration:
    jobs:
      - checkout_and_unit_test
      - integration:
          requires:
            - checkout_and_unit_test
